_name_: MTSplice
name_or_path: MTSplice  # This can be used by your factory function to pick
seq_len: 400         # Input sequence length
maxpooling: true
stride: 1            # Stride for convolution
pad_motif: 4         # Padding motifs to match original template_model setup
num_of_response: 1   # You can change this depending on regression head targets
