seq_len: 400  
train_data_file: ${oc.env:CONTRASTIVE_ROOT}/data/pretrain_sample_data/train_merged_filtered_min30Views.pkl
val_data_file: ${oc.env:CONTRASTIVE_ROOT}/data/pretrain_sample_data/val_merged_filtered_min30Views.pkl
test_data_file: ${oc.env:CONTRASTIVE_ROOT}/data/pretrain_sample_data/test_merged_filtered_min30Views.pkl
batch_size_per_device: ${div_up:${task.global_batch_size}, ${eval:${trainer.devices}  * ${trainer.num_nodes}}} 
num_workers: ${optimal_workers:}
train_ratio: 0.8       
val_ratio:  0.1
test_ratio: null      
cache_dir: "../data"         
n_augmentations: 2  # how many augmentations (homologs) you would like to choose; # or 3, or 'all' (quotes needed for string)
fixed_species: false # if want to choose fixed species as positive pairs across batch, not randomly sampled
fivep_ovrhang: 300  # how much overhang to include from 5'  intron
threep_ovrhang: 300 # how much overhang to include from 3'  intron