seq_len: 400  # PSI regression uses sequences of 201 bp (adjust if needed)
train_files:
  intronexon: ${oc.env:CONTRASTIVE_ROOT}/data/finetune_sample_data/psi_train_Retina___Eye_psi_MERGED.pkl
val_files:
  intronexon: ${oc.env:CONTRASTIVE_ROOT}/data/finetune_sample_data/psi_val_Retina___Eye_psi_MERGED.pkl
test_files:
  intronexon: ${oc.env:CONTRASTIVE_ROOT}/data/finetune_sample_data/psi_test_Retina___Eye_psi_MERGED.pkl
batch_size_per_device: ${div_up:${task.global_batch_size}, ${eval:${trainer.devices} * ${trainer.num_nodes}}}
num_workers: ${optimal_workers:}  # Increase for faster data loading
cache_dir: "../data"
fivep_ovrhang: 300  # how much overhang to include from 5'  intron
threep_ovrhang: 300 # how much overhang to include from 3'  intron
ascot: True
