exp_name: pretrain_${now:%Y_%m_%d_%H_%M_%S}
output_dir: ${oc.env:CONTRASTIVE_ROOT}/output/${exp_name}

defaults:
  - _self_
  - embedder: mtsplice
  - dataset: introns
  - task: introns_cl
  - trainer: default_trainer
  - callbacks: default_callbacks
  - tokenizer: onehot_tokenizer
  - loss: supcon
  - model: simclr
  - optimizer: adam

hydra:
  run:
    dir: ${output_dir}/hydra
    
  job:
    chdir: false

wandb:
  api_key: "74039ca49d997b68513cb2800f4397b9128a7b54"
  dir: ${output_dir}/wandb
  
logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  name: ${embedder._name_}-${dataset.seq_len}-brkpnt
  id: ${task._name_}-${.name}
  project: INTRONS_CL
  group: ${task._name_}
  save_dir: ${wandb.dir}  
  log_model: true
  notes: ""
  settings:
    init_timeout: 600
  